### ISSUE TITLE
Can't refresh charts or add USB Dogle

### ISSUE THREAD

**Issue by sailing12388** [bdbcat/o-charts_pi#44]
I have two Debian 12 systems running OpenCPN 5.8.4 with o-charts plugin 2.0.1.9.  One system works perfectly with both a dongle and a simple fingerprint.

The other system fails to see the dongle (it does show in the system) and will not accept the username/password when I try to refresh the charts (even though the list of charts show).

I've completely deleted the OpenCPN settings and reset everything and still have the same issue.

The two errors I get are 
 "USB key dongle not detected"

and (when trying to refresh the chart list)
"o-Charts shop interface error 3f void password"

**Comment by bdbcat** [comment]
On the system failing to detect dongle:
Please try:
$sudo apt install libusb-0.1-4

On the password:
Are you using any "special" characters?  Best with plain ASCII

**Comment by sailing12388** [comment]
libusb-0.1-4 is installed.  I get this in dmseg:
[2830920.664743] usb 4-2: USB disconnect, device number 8
[2830920.664752] usb 4-2.1: USB disconnect, device number 9
[2830923.060252] usb 4-2: new full-speed USB device number 13 using xhci_hcd
[2830923.225016] usb 4-2: New USB device found, idVendor=1547, idProduct=1000, bcdDevice= 0.01
[2830923.225023] usb 4-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[2830923.225025] usb 4-2: Product: SG-Lock USB Key
[2830923.225026] usb 4-2: Manufacturer: SG-Lock

I've changed the password to a very basic text only one.

**Comment by sailing12388** [comment]
blank

**Comment by bdbcat** [comment]
Not like this?

dsr@debian:~/Projects/opencpn/build$ ~/.local/bin/oexserverd -a
dsr@debian:~/Projects/opencpn/build$ oexserverd Version 1.21

**Comment by sailing12388** [comment]
I get that on the system that works but not on the other one.

ray@XPS13:~$ ~/.local/bin/oexserverd -a
ray@XPS13:~$ oexserverd Version 1.21

**Comment by bdbcat** [comment]
$ ls -l ~/.local/bin

**Comment by sailing12388** [comment]
-rw-r--r-- 1 xps xps  37586 Dec 20 21:08 libsgllnx64-2.29.02.so
-rwxr-xr-x 1 xps xps 125432 Dec 20 21:08 oexserverd

**Comment by bdbcat** [comment]
$ ldd ~/.local/bin/oexserverd

**Comment by sailing12388** [comment]
linux-vdso.so.1 (0x00007ffcef4e8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feb7d339000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007feb7d334000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007feb7cc00000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007feb7d314000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feb7ce1f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007feb7d233000)
	/lib64/ld-linux-x86-64.so.2 (0x00007feb7d356000)

**Comment by bdbcat** [comment]
Is this the same issue resolved here?
https://www.cruisersforum.com/forums/f134/o-charts-frustrations-282532-2.html#post3857312

If so, please close.

**Comment by tmaczukin** [comment]
@dbdcat I'm seeing the same problem with password as sailing12388 did.

OpenCPN version `5.8.4`

o-charts plugin version `2.0.6.0`

My password contains only ASCII characters **and works without problems in the o-charts.org shop!** Yet, I still get

> o-Charts shop interface error 3f void password

when providing my credentials on charts refresh.

**Comment by tmaczukin** [comment]
Okay, following the suggestion from https://github.com/bdbcat/o-charts_pi/issues/48#issuecomment-2119539418 (previously I've ignored this issue as I'm not using the USB dongle on this system) I decided to give it a shot and I've stopped and removed all containers and networks created by Docker. And now communication with the shop passed without any further problems.

So something is definitely wrong here :slightly_smiling_face:
